playbook.yml
Add redis-server and redis-tools to playbook.
=> add redis to playbook

requirements.txt, sesh/settings.py, seshdash/models.py
django-geoposition looks good. https://github.com/philippbosch/django-geoposition/
Another alternative is django-location-field https://github.com/caioariede/django-location-field/
=> trying django-geoposition package for site location for issue #36

.gitignore, .travis.yml, sesh/settings.py, settings_local_example.ini
tesing to see if this fix CI testing
=> re adding example configuration file for CI testing fix

seshdash/data/db/influx.py, seshdash/models.py, seshdash/tasks.py, seshdash/tests/test_tasks.py
A couple new features in this PR.
- Added in PV Yield calculation
- Added Absolute consumption since Victron can show negative production with AC coupled systems.
- Pushing weather data to Influx per site
Data:
- Added absolute consumption to data model (note: this is only necessary for AC coupled systems)
Bug Fixes:
- Fixed a bug with BOM_data_logging task. Since the VRM account details have been moved to a different Model in the last PR this has been reflected in how the credentials are now called.
=> Net Metering from VRM further influx integration and more

.travis.yml, sesh/settings.py, seshdash/tasks.py, seshdash/utils/reporting.py, seshdash/utils/send_mail.py, templates/seshdash/mail/reporting_mail.html, templates/seshdash/mail/reporting_mail.txt
Updates:
- Added reporting and alarm templates
- Added roll-bar exception handling
- Added task tracking for celery
- Modified testing
TODO:
- Unit tests need to be added for reporting elements
- Alerting is still premature need to handle connection droping
=> Reporting and hardening

seshdash/migrations/0001_initial.py, seshdash/migrations/0003_auto_20151228_1705.py
Fixing migrations chain to work cohesively.
=> fixing migratoins chain

seshdash/data/db/influx.py, settings_local_example.ini
Update:
- Fixed settings_local_example to reflect most up to date settings
- Fixed influxdb to log exceptions as strings.
=> Login bug fixes

seshdash/models.py, seshdash/sesh-ui/css/sesh.css, seshdash/sesh-ui/js/sesh_dashboard.js, seshdash/urls.py, seshdash/views.py, templates/seshdash/alerts.html
Enhanced Modal to support: 
- Ajax loading of extra alert information
- Ajax silencing of alerts 
Made the modal look cleaner
=> Modal ajax functionality

requirements.txt, sesh/settings.py, seshdash/sesh-ui/css/sesh.css, seshdash/sesh-ui/js/maps.js, seshdash/sesh-ui/js/sesh_dashboard.js, seshdash/sesh-ui/js/sesh_react.js, seshdash/urls.py, seshdash/utils/time_utils.py, seshdash/views.py, templates/seshdash/alerts.html, templates/seshdash/base.html, templates/seshdash/high_chart_line_bar.html, templates/seshdash/main-dash.html, templates/seshdash/status-card.html
System alerts now using react
Ajax alert updates after every five minutes
Immediate alert hide after silencing
=> updated the seshdashboard react window to use reactjs

seshdash/utils/time_utils.py, seshdash/views.py
=> Fixed bugs in the status card

sesh/settings.py, seshdash/sesh-ui/js/sesh_dashboard.js, templates/seshdash/base.html
- I added a nano progressbar to dashboard on load
- Timing is a bit off this can be corrected in the future
=> adding progressbar to dashboard links

seshdash/models.py, seshdash/tasks.py, seshdash/views.py
Fixing small bug in how rules were getting set.
=> Auto rules

sesh/settings.py, seshdash/sesh-ui/js/sesh_dashboard.js, seshdash/urls.py, seshdash/views.py, templates/seshdash/alerts.html, templates/seshdash/base.html
i have added a drop down notification box which contains each site and it's alerts
when the user click on a row containing a site with it's number of alerts he is directed to
the alert panel corresponding to the referenced site.
i have also configured the loading bar on the dashboard now when an event ends the bar 
now disappears .
=> Added an Alert-Notification Box and configured the loading progress bar

.gitignore, seshdash/static/sesh-ui/css/sb-admin-2.css, seshdash/static/sesh-ui/css/sb-admin-2.css_bkp, seshdash/static/sesh-ui/css/sb-admin-rtl.css, seshdash/static/sesh-ui/css/sb-admin.css, seshdash/static/sesh-ui/css/sesh.css, seshdash/static/sesh-ui/css/timeline.css, seshdash/static/sesh-ui/js/maps.js, seshdash/static/sesh-ui/js/sb-admin-2.js, seshdash/static/sesh-ui/js/sesh_dashboard.js
- Quick PR to fix sesh-ui folder copying  issue. With this update copying the sesh-ui folder is no longer necessary after changes.
=> modifying git ignore to ignore everything but sesh-ui

.gitignore, seshdash/admin.py, seshdash/models.py
- Made quick changes to admin.py and models.py to make presentation of items better
=> making models pretty and admin interface more usefull

seshdash/views.py
=> Fixed bug in get_latest_bom_data view

sesh/settings.py, seshdash/tests/data_generation.py, seshdash/tests/test_aggregate.py, seshdash/utils/alert.py
Moved the create_test_data function to the data_generation module
=> Data generation

seshdash/tasks.py, seshdash/tests/test_aggregate.py
- Historical import would fail if data contains a key that does not exits. Changing way the fields are called to using `get` so it's more resilient.
- FIgure out way to automatically find names of fields that the CSV will contain
=> Historical bug fix

sesh/settings.py, seshdash/tasks.py, seshdash/utils/time_utils.py
Fixing bug in time_zone adding of BoM data point task
=> fixing timezone

seshdash/api/victron.py, seshdash/tasks.py, seshdash/tests/test_import.py, seshdash/utils/time_utils.py
- Fixing timezone 
- Updating commenting in Victron api
- Modified Victron API to be resilient to keys not existing.
=> Timezone bug fix

seshdash/tasks.py, seshdash/tests/test_rmc_status.py
- Data point sorting was incorrect. Fixed this to prevent wrong rmc last contact calculation.
=> Rmc status bug fix

seshdash/static/sesh-ui/js/sesh_dashboard.js, seshdash/tests/test_alerts.py, seshdash/utils/send_slack.py, seshdash/views.py
Fixed the bug
Clossing issue #170
=> Fixing alert silencing bug

seshdash/static/sesh-ui/css/sesh.css, seshdash/static/sesh-ui/js/sesh_dashboard.js, seshdash/tests/test_alerts.py, seshdash/utils/send_slack.py, seshdash/views.py
Added the handle to draggable panels
=> Draggable panels

sesh/settings.py, seshdash/static/sesh-ui/js/sesh_dashboard.js, settings_local_example.ini
Moddified the settings_local_example.ini 
---------------------------------------------------
Changed the LOGGING_LEVEL = DEBUG to LOGGING_LEVEL = INFO
=> Seshdash loggingg

sesh/settings.py, seshdash/tasks.py
-  Small bugs around logging formating changed
- Removed debug logging statements
- Added proper logging to `get_BOM_data` task
=> [WIP] Bug fixes alp

seshdash/tasks.py, update.sh
- based on http://stackoverflow.com/questions/16037020/djangos-timezone-now-does-not-show-the-right-time `timezone.now` provides UTC only need to use it in conjunction with t`imezone.localtime` 
- #175 fix attempt
=> switching to timezone.localtime

sesh/settings.py, seshdash/admin.py, seshdash/data/db/influx.py, seshdash/tasks.py, seshdash/views.py, update.sh
=> Bug fixes alp

sesh/settings.py
* Fixed bug about the logger not defined in settings
* Logging messages in the sesh.settings are not handled
=> fixing bug

seshdash/forms.py, seshdash/tests/test_login.py
#Update:
- Removing auto timezone quierying based on location. This is quite resource intensive and not that usefull. Causing bugs removing for now.
=> removing auto timezone due to timeout #fixlater

seshdash/tasks.py
fix for #269 
- Removing unused RMC account object request.
=> Fixing RMC status bug

seshdash/admin.py, seshdash/models.py, seshdash/utils/model_tools.py, seshdash/views.py
- Fix #307 realized these were moved to site measurements.
- Added defaults for aggregate values for site measurements model
- Removed SI_units as this is redundant
=> add defaults to measuremnt model

seshdash/forms.py, seshdash/tests/test_edit_site.py, seshdash/views.py, templates/seshdash/settings.html, templates/seshdash/table.html
Enhanced the functionality to edit a site by adding a distinction betweeen a rmc site and a vrm site.
Fixing issue #315
=> Fixing issues

seshdash/utils/send_sms.py
Fixing sms bug.
Closing issue .. #335
=> fixed bug in sending sms

seshdash/tasks.py
Fixing #331 
- Status dp were getting put into influx for all infulx entries, including aggregates.
=> send_to_influx was creating status for all influx points

seshdash/data/db/influx.py, seshdash/data/trend_utils.py, seshdash/models.py, seshdash/tasks.py
=> [WIP] adding new models for aggregate functions

seshdash/api/victron.py, seshdash/forms.py, seshdash/static/sesh-ui/css/sesh.css, seshdash/tests/test_import.py, seshdash/tests/test_status_card.py, seshdash/urls.py, seshdash/views.py, templates/seshdash/edit-status-card.html, templates/seshdash/high_chart_line_bar.html, templates/seshdash/main-dash.html, templates/seshdash/status-card.html
* Functionality to edit status_card
* Enhcancing the ui
=> added functionality to edit status card
